from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np
from numpy.typing import NDArray


FloatArray = NDArray[np.float64]


def sample_product_simplex_distribution(
    d: int,
    L: int,
    rng: np.random.Generator | None = None,
) -> FloatArray:
    """Return one sample from the product-simplex distribution.

    The sample is a probability vector of length ``d``. It is generated by
    drawing ``L`` independent uniform simplex vectors, multiplying them
    componentwise, and normalizing once at the end.
    """

    out = np.empty(_validate_positive_int(d, "d"), dtype=np.float64)
    work = np.empty_like(out)
    return fill_product_simplex_sample(out=out, L=L, rng=rng, work=work)


def fill_product_simplex_sample(
    out: FloatArray,
    L: int,
    rng: np.random.Generator | None = None,
    work: FloatArray | None = None,
) -> FloatArray:
    """Fill ``out`` with one product-simplex sample and return ``out``.

    Providing ``work`` avoids per-call temporary allocation. Both ``out`` and
    ``work`` must be one-dimensional ``float64`` arrays of the same length.
    """

    _validate_output_array(out, "out")
    L = _validate_positive_int(L, "L")

    if work is None:
        work = np.empty_like(out)
    else:
        _validate_output_array(work, "work")
        if work.shape != out.shape:
            raise ValueError("work must have the same shape as out")
        if np.shares_memory(out, work):
            raise ValueError("work must not share memory with out")

    generator = rng if rng is not None else np.random.default_rng()

    out.fill(0.0)
    tiny = np.finfo(np.float64).tiny
    for _ in range(L):
        generator.random(size=out.shape, dtype=np.float64, out=work)

        # If U is uniform on (0, 1), then -log(U) is Exp(1). Therefore
        # log(-log(U)) is the log of one exponential simplex weight.
        np.maximum(work, tiny, out=work)
        np.log(work, out=work)
        np.negative(work, out=work)
        np.log(work, out=work)
        out += work

    _normalize_log_weights_in_place(out)
    return out


@dataclass
class ProductSimplexSampler:
    """Reusable sampler for repeated product-simplex draws."""

    d: int
    L: int
    rng: np.random.Generator = field(default_factory=np.random.default_rng)

    def __post_init__(self) -> None:
        self.d = _validate_positive_int(self.d, "d")
        self.L = _validate_positive_int(self.L, "L")
        self._work = np.empty(self.d, dtype=np.float64)

    def sample(self, out: FloatArray | None = None) -> FloatArray:
        """Return one probability vector, optionally filling ``out`` in place."""

        if out is None:
            out = np.empty(self.d, dtype=np.float64)
        else:
            _validate_output_array(out, "out")
            if out.shape != self._work.shape:
                raise ValueError("out has the wrong shape")

        return fill_product_simplex_sample(
            out=out,
            L=self.L,
            rng=self.rng,
            work=self._work,
        )


def _normalize_log_weights_in_place(log_weights: FloatArray) -> None:
    log_weights -= log_weights.max()
    np.exp(log_weights, out=log_weights)
    log_weights /= log_weights.sum(dtype=np.float64)


def _validate_positive_int(value: int, name: str) -> int:
    if not isinstance(value, int):
        raise TypeError(f"{name} must be an integer")
    if value <= 0:
        raise ValueError(f"{name} must be positive")
    return value


def _validate_output_array(array: FloatArray, name: str) -> None:
    if array.ndim != 1:
        raise ValueError(f"{name} must be one-dimensional")
    if array.size == 0:
        raise ValueError(f"{name} must not be empty")
    if array.dtype != np.float64:
        raise TypeError(f"{name} must have dtype float64")

